spring.application.name=ms-pedidos360-bff
server.port=8080

# Configuracion Entra ID / Azure AD
spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.credential.client-id=5af7fc33-4e8a-44b1-b7cc-ee03d528a780
spring.cloud.azure.active-directory.profile.tenant-id=ed56c829-2496-4428-8515-1cf215407742
spring.cloud.azure.active-directory.app-id-uri=api://5af7fc33-4e8a-44b1-b7cc-ee03d528a780

# Resource Server OAuth2 JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/ed56c829-2496-4428-8515-1cf215407742/v2.0

logging.level.org.springframework.security=DEBUG