spring.application.name=ms-pedidos360-bff

server.port=8080

services.orders.base-url=${ORDERS_SERVICE_URL:http://localhost:8081}
services.catalog.base-url=${CATALOG_SERVICE_URL:http://localhost:8082}
services.report.base-url=${REPORT_SERVICE_URL:http://localhost:8084}

logging.level.org.springframework.security=DEBUG